### ISSUE TITLE
Data does not accessible in `plot_size_factor_effect_on_dim_reduction.Rmd`

### ISSUE THREAD

**Issue by kuang-da** [const-ae/transformGamPoi-Paper#5]
Hi,

Thank you for the great work and the paper is very inspiring. I am trying to reproduce the figure in `plot_size_factor_effect_on_dim_reduction.Rmd` but I notice that the URL is not available anymore. 

Would you please release the data for this figure? Thank you! 

```
> if(! file.exists("../extra_data//svensson_2017_1.h5ad")){
  download.file("https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/", "../extra_data/svensson_2017_1.h5ad")
}

trying URL 'https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/'
Error in download.file("https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/",  : 
  cannot open URL 'https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/'
In addition: Warning messages:
1: In download.file("https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/",  :
  downloaded length 0 != reported length 0
2: In download.file("https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/",  :
  cannot open URL 'https://data.caltech.edu/tindfiles/serve/3f89d3a5-6ceb-486e-95d4-9bd3f511a706/': HTTP status was '404 Not Found'
```

**Comment by const-ae** [comment]
Hi Da,

thanks for reaching out and alerting me to this issue.

For now, here is a link to the orginal file [svensson_2017_1.h5ad.zip](https://github.com/const-ae/transformGamPoi-Paper/files/12511626/svensson_2017_1.h5ad.zip). 
In addition, I will try to investigate why the caltech data repository disappeared and if necessary will replace the broken links.

Best,
Constantin

**Comment by const-ae** [comment]
Okay, the original repo from which I downloaded the data is at https://data.caltech.edu/records/6fy1w-dgm81 (the original link https://data.caltech.edu/records/1264 forwards to the new location, but the file downloads, unfortunately, do not). I checked the file hash for my local copy of the file and the one that you can download from the new location. I will update the link in the markdown file to avoid other people running into the same issue.
